url: 'https://servicodeafiliados.github.io/'
baseurl: '/700receitas'
title: '700 Receitas Zero Açúcar e Glúten'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
