url: 'https://servicodeafiliados.github.io/'
baseurl: '700receitas'
title: '700receitas'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
